models/Tutor.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

use yii\helpers\VarDumper;

/**
 * This is the model class for table "tutor".
 *
 * @property integer $id
 * @property string $bio
 * @property string $address
 * @property resource $photo
 * @property boolean $canSetOwnPrice
 */
class Tutor extends \yii\db\ActiveRecord
{
	/**
	 * @var UploadedFile
	 */
	public $imageFile;


	/**
	* @inheritdoc
	*/
	public static function tableName()
	{
		return 'tutor';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[ [ 'id', 'maxDiscountMinsRecurring', 'minDiscountMinsRecurring', 'minDiscountHoursFlex', 'maxDiscountHoursFlex',
				'maxPPMRecurring', 'minPPMRecurring', 'maxPPHFlex', 'maxPPHFlex' ], 'required' ],
			[ [ 'id', 'maxDiscountMinsRecurring', 'minDiscountMinsRecurring', 'maxDiscountHoursFlex', 'minDiscountHoursFlex' ], 'integer' ],
			[ [ 'photo' ], 'safe' ],
			[ [ 'maxPPMRecurring', 'minPPMRecurring', 'maxPPHFlex', 'maxPPHFlex' ], 'number' ],
			[ [ 'bio', 'address' ], 'string', 'max' => 255 ],
			[ [ 'canSetOwnPrice' ], 'safe' ],
			[ [ 'imageFile' ], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif' ],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => Yii::t( 'app', 'ID' ),
			'bio' => Yii::t( 'app', 'Bio' ),
			'address' => Yii::t( 'app', 'Address' ),
			'photo' => Yii::t( 'app', 'Photo' ),
			'canSetOwnPrice' => Yii::t( 'app', 'Can set their own price?' ),
			'imageFile' => Yii::t( 'app', 'Photo' ),
			'maxPPMRecurring' => Yii::t( 'app', 'Maximum Price/Min (Recurring)' ),
			'minPPMRecurring' => Yii::t( 'app', 'Minimum Price/Min (Recuring)' ),
			'maxDiscountMinsRecurring' => Yii::t( 'app', 'Maximum Minutes for Discounts (Recurring)' ),
			'minDiscountMinsRecurring' => Yii::t( 'app', 'Minimum Minutes for Discounts (Recurring)' ),
			'maxPPHFlex' => Yii::t( 'app', 'Maximum Price/Hr (Flex)' ),
			'minPPHFlex' => Yii::t( 'app', 'Minimum Price/Hr (Flex)' ),
			'maxDiscountHoursFlex' => Yii::t( 'app', 'Maximum Hours for Discounts (Flex)' ),
			'minDiscountHoursFlex' => Yii::t( 'app', 'Minimum Hours for Discounts (Flex)' ),
		];
	}

	/**
	 * Returns the user record associated with this tutor
	 */
	public function getUser()
	{
		return $this->hasOne( User::classname(), [ 'id' => 'id' ] );
	}

	/**
	 * Saves the uploaded image into the photo field
	 */
	public function upload()
	{
		if ( $this->validate() )
		{
			$this->photo = file_get_contents( $this->imageFile->tempName );
			return true;
		}
		else
		{
			return false;
		}
	}

	/**
	 * @inheritdoc
	 * @return TutorQuery the active query used by this AR class.
	 */
	public static function find()
	{
		return new TutorQuery( get_called_class() );
	}

	public function getRecurringPricesString()
	{
		return '{ minutes:0, price:0.05 }, { minutes:80, price:0.045 }, { minutes:120, price:0.044 }';
	}

	public function loadDefaultPrices()
	{
		$this->maxPPMRecurring = Settings::getHighestPricePerMinuteRecurring();
		$this->minPPMRecurring = Settings::getLowestPricePerMinuteRecurring();
		$this->maxDiscountMinsRecurring = Settings::getMaximumMinutesForDiscountsRecurring();
		$this->minDiscountMinsRecurring = Settings::getMinimumMinutesForDiscountsRecurring();
		
		$this->maxPPHFlex = Settings::getHighestPricePerHourFlex();
		$this->minPPHFlex = Settings::getLowestPricePerHourFlex();
		$this->maxDiscountHoursFlex = Settings::getMaximumHoursForDiscountsFlex();
		$this->minDiscountHoursFlex = Settings::getMinimumHoursForDiscountsFlex();
	}

	public function getAvailableTimes( $timezone )
	{
		$availableTimes = array();
		$times = AvailableTime::find()->where( [ 'tutorId' => $this->id ] )->all();
		$custTZ = new \DateTimeZone( $timezone );
		$tutorTZ = new \DateTimeZone( $this->user->timezone );

		// loop through all the times from the db
		foreach ( $times as $time )
		{
			$newTime = array();

			// get the current date/time of the tutor
			$curDate = new \DateTime( "now", $tutorTZ );

			// convert the tutor's current day of week to a number
			$curDOW = $this->convertDOWToNum( $curDate->format( 'l' ) );

			// get the difference between the day of week of the available time and the current day of week
			$diff = $time->dayOfWeek - $curDOW;
			$interval = new \DateInterval( 'P' . abs( $diff ) . 'D' );

			// if the difference negative, we need to invert the interval
			if ( $diff < 0 )
			{
				$interval->invert = true;
			} // if ( $diff < 0 )

			// calculate the new start/end dates
			$newStartDate = $curDate->add( $interval );
			$newEndDate = new \DateTime( $curDate->format( 'Y-m-d H:i:s' ), $tutorTZ );

			// set the time of the new start/end dates
			$arr = explode( ':', $time->startTime );
			$newStartDate->setTime( intval( $arr[ 0 ] ), intval( $arr[ 1 ] ) );
			$arr = explode( ':', $time->endTime );
			$newEndDate->setTime( intval( $arr[ 0 ] ), intval( $arr[ 1 ] ) );

			// we now need to convert to customer's timezone
			$newStartDate->setTimezone( $custTZ );
			$newEndDate->setTimezone( $custTZ );

			$newTime[ 'dow' ] = array( [ $this->convertDOWToNum( $newStartDate->format( 'l' ) ) ] );
			$newTime[ 'start' ] = $newStartDate->format( 'H:i' );
			$newTime[ 'end' ] = $newEndDate->format( 'H:i' );
			$availableTimes[] = $newTime;
		} // foreach ( $times as $time )

		return $availableTimes;
	}	

	private function convertDOWToNum( $dow )
	{
		switch ( $dow )
		{
			case 'Sunday':
				return 0;

			case 'Monday':
				return 1;

			case 'Tuesday':
				return 2;

			case 'Wednesday':
				return 3;

			case 'Thursday':
				return 4;

			case 'Friday':
				return 5;

			case 'Saturday':
				return 6;

			default:
				throw new \Exception;
		}
	}
}

controllers/TutorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tutor;
use app\models\TutorSearch;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\User;
use app\models\Phone;
use app\models\VideoChat;
use app\models\AvailableTime;
use yii\web\UploadedFile;
use yii\web\Response;
use yii2fullcalendar\models\Event;

use yii\helpers\VarDumper;

/**
 * TutorController implements the CRUD actions for Tutor model.
 */
class TutorController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => [ 'prices' ],
						'allow' => true,
						'roles' => [ '@' ]
					],
					[
						'actions' => [ 'view' ],
						'allow' => true,
						'matchCallback' => function ( $rule, $action ) {
							$model = $this->findModel( Yii::$app->getRequest()->get( 'id' ) );
							return Yii::$app->getUser()->can( 'viewTutor', [ 'tutor' => $model ] );
						}
					],
					[
						'actions' => [ 'index', 'create', 'emails', 'delete' ],
						'allow' => true,
						'roles' => [ 'admin' ],
					],
					[
						'actions' => [ 'contact-info' ],
						'allow' => true,
						'roles' => [ 'customer' ]
					],
					[
						'actions' => [ 'add-phone', 'add-video-chat', 'add-email' ],
						'allow' => true,
						'matchCallback' => function ( $rule, $action ) {
							$model = $this->findModel( Yii::$app->getRequest()->get( 'userId' ) );
							return Yii::$app->getUser()->can( 'updateTutor', [ 'tutor' => $model ] );
						}
					],
					[
						'actions' => [ 'update', 'available' ],
						'allow' => true,
						'matchCallback' => function ( $rule, $action ) {
							$model = $this->findModel( Yii::$app->getRequest()->get( 'id' ) );
							return Yii::$app->getUser()->can( 'updateTutor', [ 'tutor' => $model ] );
						}
					],
					[
						'actions' => [ 'tasks' ],
						'allow' => true,
						'roles' => [ 'tutor' ],
					],
					[
						'actions' => [ 'emails' ],
						'allow' => true,
						'roles' => [ 'admin' ],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => [ 'POST' ],
				],
			],
		];
	}

	/**
	 * Lists all Tutor models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new TutorSearch();
		$dataProvider = $searchModel->search( Yii::$app->request->queryParams );

		return $this->render( 'index', [ 'searchModel' => $searchModel, 'dataProvider' => $dataProvider ] );
	}

	// only accessible to logged in customers
	public function actionContactInfo()
	{
		$searchModel = new TutorSearch();
		$dataProvider = $searchModel->searchCustomerTutors( Yii::$app->user->id );

		return $this->render( 'contactInfo', [ 'dataProvider' => $dataProvider ] );
	}

	/**
	 * Displays a single Tutor model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView( $id )
	{
		return $this->render( 'view', [ 'model' => $this->findModel( $id ) ] );
	}

	/**
	 * Creates a new Tutor model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new Tutor();
		$user = new User();
		$phone = new Phone();
		$videoChat = new VideoChat();

		// load the default prices
		$model->loadDefaultPrices();

		// if we loaded the information from the post back
		if ( $model->load( Yii::$app->request->post() ) &&
			  $user->load( Yii::$app->request->post() ) &&
			  $phone->load( Yii::$app->request->post() ) &&
			  $videoChat->load( Yii::$app->request->post() ) )
		{
			$user->setPassword( $user->password );
			$user->type = User::TYPE_TUTOR;

			$transaction = Yii::$app->db->beginTransaction();

			try
			{
				// if the user model was saved
				if ( $user->save() )
				{
					$model->id = $user->id;
					$model->imageFile = UploadedFile::getInstance( $model, 'imageFile' );

					// if the image file is not empty
					if ( !empty( $model->imageFile ) )
					{
						// if we successfully saved the image
						if ( !$model->upload() )
						{
							$transaction->rollback();
							//TODO: Probably need to show some kind of error
							return $this->refresh();
						} // if ( !$model->upload() )
					} // if ( !empty( $model->imageFile ) )

					// if the tutor model itself was saved
					if ( $model->save() )
					{
						$auth = Yii::$app->authManager;
						$tutorRole = $auth->getRole( 'tutor' );
						$auth->assign( $tutorRole, $model->id );
						$phone->userId = $user->id;

						// if the phone record was saved
						if ( $phone->save() )
						{
							$videoChat->userId = $user->id;
							$videoChat->isPrimary = true;

							// if the video chat was saved
							if ( $videoChat->save() )
							{
								$transaction->commit();
								return $this->redirect( [ 'view', 'id' => $model->id ] );
							} // if ( $videoChat->save() )
						} // if ( $phone->save() )
					} // if ( $model->save() )
				} // if ( $user->save() )

				$transaction->rollback();
				return $this->refresh();
			} // try
			// let's catch all exceptions and rollback the transaction
			catch ( Exception $e )
			{
				$transaction->rollback();
			} // catch ( Exception $e )
		} // if ( $model->load( Yii::$app->request->post() ) &&.......

		return $this->render( 'create', [ 'model' => $model, 'user' => $user, 'phone' => $phone, 'videoChat' => $videoChat ] );
	}

	/**
	 * Updates an existing Tutor model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate( $id )
	{
		$user = User::findOne( $id );
		$model = $this->findModel( $id );
//		$phones = Phone::find()->where( [ 'userId' => $id ] )->all();
//		$videoChats = VideoChat::find()->where( [ 'userId' => $id ] )->all();

		if ( $model->load( Yii::$app->request->post() ) &&
			  $user->load( Yii::$app->request->post() ) )
		{
			$transaction = Yii::$app->db->beginTransaction();

			try
			{
				if ( $user->save() )
				{
					$model->imageFile = UploadedFile::getInstance( $model, 'imageFile' );
					$canContinue = FALSE;

					if ( !empty( $model->imageFile ) )
					{
						if ( !$model->upload() )
						{
							$transaction->rollback();
							return $this->refresh();
						}
					}

					if ( $model->save() )
					{
						$transaction->commit();
						return $this->redirect( [ 'view', 'id' => $model->id ] );
					}
				}

				$transaction->rollback();
				return $this->refresh();
			}
			catch ( Exception $e )
			{
				$transaction->rollback();
			}
		}

		return $this->render( 'update', [ 'model' => $model, 'user' => $user ] );
	}

	public function actionTasks()
	{
		$model = $this->findModel( Yii::$app->user->id );

		return $this->render( 'tasks', [ 'model' => $model ] );
	}

	public function actionAddPhone( $userId, $returnUrl )
	{
		$phone = new Phone();

		if ( $phone->load( Yii::$app->request->post() ) )
		{
			$phone->userId = $userId;
			$phone->save();
			return $this->redirect( $returnUrl ? urldecode( $returnUrl ) : [ 'view', 'id' => $userId ] );
		}
		else //if ( Yii::$app->request->isAjax )
		{
			return $this->renderAjax( 'phone', [ 'model' => $phone ] );
		}
	}

	public function actionAddVideoChat( $userId )
	{
		$videoChat = new VideoChat();

		if ( $videoChat->load( Yii::$app->request->post() ) )
		{
			$videoChat->userId = $userId;
			$videoChat->save();
			return $this->redirect( [ 'view', 'id' => $userId ] );
		}
		else //if ( Yii::$app->request->isAjax )
		{
			return $this->renderAjax( 'videoChat', [ 'model' => $videoChat ] );
		}
	}

	/**
	 * Deletes an existing Tutor model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete( $id )
	{
		$user = User::findOne( $id );
		$user->status = User::STATUS_DELETED;
		$user->save();

		return $this->redirect( [ 'index' ] );
	}

	/**
	 * Displays a list of tutor email addresses
	 *
	 */
	public function actionEmails()
	{
		$searchModel = new TutorSearch();
		$dataProvider = $searchModel->searchEmail( Yii::$app->request->queryParams );

		return $this->render( 'emails', [ 'searchModel' => $searchModel, 'dataProvider' => $dataProvider ] );
	}

	private function convertDOWToNum( $dow )
	{
		switch ( $dow )
		{
			case 'Sunday':
				return 0;

			case 'Monday':
				return 1;

			case 'Tuesday':
				return 2;

			case 'Wednesday':
				return 3;

			case 'Thursday':
				return 4;

			case 'Friday':
				return 5;

			case 'Saturday':
				return 6;

			default:
				throw new \Exception;
		}
	}

	private function getLocalDateTime( $time, $dayOfWeek, $tutorTimezone )
	{
		// get current date/time of tutor
		$curDate = new \DateTime( "now", new \DateTimeZone( $tutorTimezone ) );

		// get current day of week
		$curDOW = $this->convertDOWToNum( $curDate->format( 'l' ) );

		// find the difference between the available time day of week and the current day of week 
		$diff = $dayOfWeek - $curDOW;
		$interval = new \DateInterval( 'P' . abs( $diff ) . 'D' );

		// if the difference is negative, we will need to invert the interval
		if ( $diff < 0 )
		{
			$interval->invert = true;
		} // if ( $diff < 0 )

		// calculate the new date
		$newDate = $curDate->add( $interval );

		// set the time of th new date
		$arr = explode( ':', $time );
		$newDate->setTime( intval( $arr[ 0 ] ), intval( $arr[ 1 ] ) );

		return $newDate;
	}

	public function actionPrices( $id )
	{
		$tutor = $this->findModel( $id );

		Yii::$app->response->format = Response::FORMAT_JSON;

		return [
			'minPPMRecurring' => $tutor->minPPMRecurring,
			'maxPPMRecurring' => $tutor->maxPPMRecurring,
			'minMinsForDiscount' => $tutor->minDiscountMinsRecurring,
			'maxMinsForDiscount' => $tutor->maxDiscountMinsRecurring,
			'minPPHFlex' => $tutor->minPPHFlex,
			'maxPPHFlex' => $tutor->maxPPHFlex,

views/tutor/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use app\models\User;
use app\models\Timezone;
use app\models\Phone;
use app\models\VideoChat;

/* @var $this yii\web\View */
/* @var $model app\models\Tutor */
/* @var $user app\models\User */
/* @var @phone app\models\Phone */				// NULL if Update
/* @var @videoChat app\models\VideoChat */	// NULL if update
/* @var $form yii\widgets\ActiveForm */

$curUser = User::findOne( Yii::$app->user->id );
?>

<div class="tutor-form">

	<?php $form = ActiveForm::begin( [ 'options' => [ 'enctype' => 'multipart/form-data' ] ] ); ?>

		<?= $form->field( $user, 'name' )->textInput() ?>

		<?= $form->field( $user, 'email' )->textInput() ?>

		<?= $form->field( $user, 'username' )->textInput() ?>

		<?= $form->field( $user, 'password' )->passwordInput() ?>

		<!-- if we are an admin creating a new record -->
		<?php if ( $model->isNewRecord ) : ?>
			<div class="row">
				<div class="col-lg-2">
					<?= $form->field( $phone, 'type' )->dropDownList( Phone::$types ) ?>
				</div>
				<div class="col-lg-2">
					<?= $form->field( $phone, 'countryCode' )->textInput( [ 'maxlength' => true ] ) ?>
				</div>
				<div class="col-lg-4">
					<?= $form->field( $phone, 'number' )->textInput() ?>
				</div>
			</div>
		<!-- else we are either an admin or the tutor himself  -->
		<?php else : ?>
			<?= $user->getPhonesHtml( Yii::$app->request->url ) ?>
		<?php endif; ?>		

		<?= $form->field( $model, 'imageFile' )->fileInput() ?>
		<?php
		// if the photo has a value, let's display it
		if ( !empty( $model->photo ) )
		{
			echo '<img src="data:image;base64,' . base64_encode( $model->photo ).'" height="200" />';
		} //if ( !empty( $model->photo ) )
		?>

		<?= $form->field( $model, 'bio' )->textArea( [ 'maxlength' => true ] ) ?>

		<?= $form->field( $model, 'address' )->textArea( [ 'maxlength' => true ] ) ?>

		<!-- if we are an admin creating a new record -->
		<?php if ( $model->isNewRecord ) : ?>
			<div class="row">
				<div class="col-lg-2">
					<?= $form->field( $videoChat, 'type' )->dropDownList( VideoChat::$types ) ?>
				</div>
				<div class="col-lg-2">
					<?= $form->field( $videoChat, 'accountId' )->textInput() ?>
				</div>
			</div>
		<!-- else we are either an admin or the tutor himself  -->
		<?php else : ?>
			<?= $user->getVideoChatsHtml( Yii::$app->request->url ) ?>
		<?php endif; ?>		

		<?= $form->field( $user, 'timezone' )->dropDownList( Timezone::$timezones ) ?>

		<?= $form->field( $user, 'notes' )->textArea() ?>

		<!-- if the current user is an admin -->
		<?php if ( $curUser->isAdmin() ) : ?>
			<?= $form->field( $user, 'notesPrivate' )->textArea() ?>
			<?= $form->field( $model, 'canSetOwnPrice' )->checkBox() ?>
			<?= $form->field( $user, 'status' )->dropDownList( [ User::STATUS_ACTIVE => 'Active', User::STATUS_INACTIVE => 'Inactive' ] ) ?>
		<?php endif; ?>

		<!-- if the current user is an admin or it is a tutor can has the ability to set their own price -->
		<?php if ( $curUser->isAdmin() || $model->canSetOwnPrice ) : ?>
			<div class="row">
				<div class="col-lg-3">
					<?= $form->field( $model, 'maxPPMRecurring' )->textInput() ?>
				</div>
				<div class="col-lg-3">
					<?= $form->field( $model, 'minPPMRecurring' )->textInput() ?>
				</div>
				<div class="col-lg-3">
					<?= $form->field( $model, 'maxDiscountMinsRecurring' )->textInput() ?>
				</div>
				<div class="col-lg-3">
					<?= $form->field( $model, 'minDiscountMinsRecurring' )->textInput() ?>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-3">
					<?= $form->field( $model, 'maxPPHFlex' )->textInput() ?>
				</div>
				<div class="col-lg-3">
					<?= $form->field( $model, 'minPPHFlex' )->textInput() ?>
				</div>
				<div class="col-lg-3">
					<?= $form->field( $model, 'maxDiscountHoursFlex' )->textInput() ?>
				</div>
				<div class="col-lg-3">
					<?= $form->field( $model, 'minDiscountHoursFlex' )->textInput() ?>
				</div>
			</div>
		<?php endif; ?>

		<div class="form-group">
			<?= Html::submitButton( $model->isNewRecord ? Yii::t( 'app', 'Create' ) : Yii::t( 'app', 'Update' ), [ 'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary' ] ) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

views/tutor/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TutorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tutor-search">

	<?php $form = ActiveForm::begin( [ 'action' => [ 'index' ], 'method' => 'get' ] ); ?>

		<div class="row">
			<div class="col-lg-4">
				<?= $form->field( $model, 'name' ) ?>
			</div>
			<div class="col-lg-4">
				<?= $form->field( $model, 'email' ) ?>
			</div>
			<div class="col-lg-4">
				<?= $form->field( $model, 'username' ) ?>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<?= $form->field( $model, 'phone' ) ?>
			</div>
			<div class="col-lg-4">
				<?= $form->field( $model, 'status' ) ?>
			</div>
			<div class="col-lg-4">
				<?= $form->field( $model, 'timezone' ) ?>
			</div>
		</div>
		<div class="form-group">
			<?= Html::submitButton( Yii::t( 'app', 'Search' ), [ 'class' => 'btn btn-primary' ] ) ?>
			<?= Html::resetButton( Yii::t( 'app', 'Reset' ), [ 'class' => 'btn btn-default' ] ) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

views/tutor/contactInfo.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\TutorSearch */
/* @var $userSearch app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t( 'app', 'Tutors' );
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="tutor-index">

	<h1><?= Html::encode( $this->title ) ?></h1>

	<?php Pjax::begin(); ?>
		<?= GridView::widget( [
			'dataProvider' => $dataProvider,
			'columns' => [
				[ 'class' => 'yii\grid\SerialColumn' ],
				'user.name',
				'user.email',
				[ 'label' => 'Phones', 'format' => 'raw', 'value' => function ( $model ) { return $model->user->getPhonesHtml( null, false ); } ],
				//'address',
				'user.timezone',
				[ 'class' => 'yii\grid\ActionColumn' ],
			],
		] ); ?>
	<?php Pjax::end(); ?>
</div>

views/tutor/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tutor */
/* @var $user app\models\User */
/* @var $phone app\models\Phone */
/* @var $videoChat app\models\VideoChat */

$this->title = Yii::t( 'app', 'Create Tutor' );
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t( 'app', 'Tutors' ), 'url' => [ 'index' ] ];
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="tutor-create">
	<h1><?= Html::encode( $this->title ) ?></h1>

	<?= $this->render( '_form', [ 'model' => $model, 'user' => $user, 'phone' => $phone, 'videoChat' => $videoChat ] ) ?>
</div>

views/tutor/phone.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Phone;
?>
<div class="phone-form">

	<?php $form = ActiveForm::begin( [ 'options' => [ 'id' => 'phone' ] ] ); ?>

		<div class="row">
			<div class="col-lg-2">
				<?= $form->field( $model, 'type' )->dropDownList( Phone::$types ) ?>
			</div>
			<div class="col-lg-2">
				<?= $form->field( $model, 'countryCode' )->textInput( [ 'maxlength' => true ] ) ?>
			</div>
			<div class="col-lg-3">
				<?= $form->field( $model, 'number' )->textInput() ?>
			</div>
		</div>

		<div class="form-group">
			<?= Html::submitButton( Yii::t( 'app', 'Add' ), [ 'class' => 'btn btn-success' ] ) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

views/tutor/tasks.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\AvailableTime;

/* @var $this yii\web\View */

$this->title = 'Booking and Billing';
?>
<div class="site-index">

	<div class="jumbotron">
		<h1>Welcome, <?= $model->user->name ?></h1>
	</div>

	<div class="body-content">
		<div class="row">
			<div class="col-lg-4">
				<?php if ( !AvailableTime::find()->where( [ 'tutorId' => $model->id ] )->exists() ) : ?>
					<p><?= Html::a( "No Available Time is currently set.  Set Now", Url::to( [ 'tutor/available' ] ) ) ?></p>
				<?php endif; ?>
				<p><?= Html::a( "Calendar", Url::to( [ 'tutor/calendar', 'id' => $model->id ] ), [ "class" => "btn btn-default" ] ) ?></p>
				<p><?= Html::a( "Invoices and Payments", Url::to( [ 'purchase/index', 'tutorId' => $model->id ] ), [ "class" => "btn btn-default" ] ) ?></p>
				<p><?= Html::a( "Student Email Addresses", Url::to( [ 'customer/emails' ] ), [ "class" => "btn btn-default" ] ) ?></p>
				<p><?= Html::a( "Student Accounts", Url::to( [ 'customer/index' ] ), [ "class" => "btn btn-default" ] ) ?></p>
				<p><?= Html::a( "My Account", Url::to( [ 'tutor/view', 'id' => $model->id ] ), [ "class" => "btn btn-default" ] ) ?></p>
			</div>
		</div>
	</div>
</div>